# Spring properties
spring:
  application:
    name: api-gateway  # Identify this application

# Server
server:
  port: 7070  # HTTP (Tomcat) port

my_message: server 7070


#  eureka.instance.prefer-ip-address=true
#  eureka.instance.ip-address=
# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true
    ip-address: 192.168.0.101
  client:
    serviceUrl:
      defaultZone: http://192.168.0.101:8080/discovery-server/eureka/
    instance:
      leaseRenewalIntervalInSeconds: false   # DO NOT DO THIS IN PRODUCTION
    registerWithEureka: true
    fetchRegistry: true


# Api-Gate-Way
zuul:
  prefix: /api
  routes:
    user-service:
      path: /user-service/**
      serviceId: USER-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie
    notification-service:
      path: /notification-service/**
      serviceId: NOTIFICATION-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: '*'
  host:
      time-to-live: -1
      connect-timeout-millis: 5000
      max-per-route-connections: 10000
      max-total-connections: 5000
      socket-timeout-millis: 60000
  semaphore:
      max-semaphores: 500


hystrix:
  command:
    default:
      execution:
        iso lation:
          thread:
            timeoutInMilliseconds: 30000


ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true



#http://localhost:7070/api/user-service/user/fetchAllCustomer/
#http://localhost:7070/api/notification-service/notification/fetchAllNotification